#ROS package you are documenting
package_name = "aeb_ros"
repo = "https://github.com/ISC-Project-Phoenix/aeb_ros"

#You can have multiple nodes in one package
[[nodes]]
node_name = 'aeb'
#Relitive to this file
source_file = ['./src/aeb.cpp']
summary = '''
Lidar based Automatic emergency braking node for ackermann drive vehicles.

See [here](https://github.com/ISC-Project-Phoenix/design/blob/main/software/embed/AEB.md) for algorithm design information.
'''

[[nodes.publishes]]
name = '/aeb_out'
description = 'Publishes messages containing the time to collision if a collision under the configured TTC is predicted.'

[[nodes.subscribes]]
name = '/odom'
description = 'Odom used to derive speed and steering info.'

[[nodes.subscribes]]
name = '/scan'
description = 'Laserscans to build the occupancy grid with. This may be incremental scans or complete scans.'

[[nodes.params]]
name = 'wheelbase'
description = 'Wheelbase of the vehicle. Default 1.8'

[[nodes.params]]
name = 'lidar_frame'
description = 'Frame of the source laserscans. Default "laser_link"'

[[nodes.params]]
name = 'min_ttc'
description = 'Minimum allowed Time To Collision (a TTC under this will trigger braking), in seconds. Default 2'

[[nodes.params]]
name = 'step_size'
description = '''
Size of a step in forward prediction, in ms. The higher this value, the lower the precision of predicted collision time,
but the better the performance. Note that this doesn't effect the accuracy of collision detection.
Default 50
'''

[[nodes.params]]
name = 'scan_region_start'
description = '''
Start of desired scan region, in degrees. Scans outside of this region will be ignored, but incremental scans that land
partially in this area will be included. If your lidar gives full scans on /scan, then this param is ignored. Such is the
case in gazebo. Default 360 - 25
'''

[[nodes.params]]
name = 'scan_region_end'
description = '''
End of desired scan region, in degrees. Scans outside of this region will be ignored, but incremental scans that land
partially in this area will be included. If your lidar gives full scans on /scan, then this param is ignored. Such is the
case in gazebo. Default 25
'''

[[nodes.params]]
name = 'collision_box'
description = '''
Collision box of the vehicle, defined as the top left and bottom right of the rectangle with repect to base_link.
This param is a string in the format [[float, float], [float, float]].
Default [[-0.675, 1.43],[0.675, -0.59]]
'''
